AWSTemplateFormatVersion: "2010-09-09"
Description: create ERC repo 
Resources:
  MyECRRepo:
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: "test-repository"
      ImageScanningConfiguration: 
        ScanOnPush: "true"
Outputs:    
  Arn:
    Value: !Join [".",[!Sub "${AWS::AccountId}", "dkr", "ecr", !Sub "${AWS::Region}", "amazonaws", "com",  !Join [ "/", [ "test-repository" ] ]]]
