AWSTemplateFormatVersion: "2010-09-09"
Description: create ERC repo 
Resources:
  MyECRRepo:
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: "test-repository"
      ImageScanningConfiguration: 
        ScanOnPush: "true"
